version: '2'

networks:
  app-tier:
    driver: bridge

services:
  mariadb:
    container_name: mariadb
    image: mariadb:10.4.6
    networks:
      - app-tier
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_USER=root
      - MYSQL_DATABASE=blog
      - POSTGRESQL_NUM_SYNCHRONOUS_REPLICAS=1
