version: '2.1'

networks:
  app-tier:
    driver: bridge

services:
  mariadb:
    image: 'bitnami/mariadb:latest'
    container_name: 'mariadb'
    ports:
      - '3306:3306'
    volumes:
      - 'mariadb_data:/bitnami/mariadb'
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      # - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_ROOT_PASSWORD=123456
      - MARIADB_USER=vampire
      - MARIADB_PASSWORD=123456
      - MARIADB_DATABASE=sonar
    healthcheck:
      test: ['CMD', '/opt/bitnami/scripts/mariadb/healthcheck.sh']
      interval: 15s
      timeout: 5s
      retries: 6
    networks:
      - app-tier

volumes:
  mariadb_data:
    driver: local
