version: '2'

networks:
  app-tier:
    driver: bridge

services:
  gitlab:
    hostname: 192.168.137.166
    container_name: gitlab
    image: 'gitlab/gitlab-ce'
    networks:
      - app-tier
    ports:
      - '443:443'
      - '8000:8000'
      - '6050:22'
    volumes:
 #     - '/tmp/gitlab/data:/var/opt/gitlab'
 #     - '/tmp/gitlab/logs:/var/log/gitlab'
      - '/tmp/gitlab/config:/etc/gitlab'
