version: '2'

networks:
  app-tier:
    driver: bridge

services:
  etcd:
    container_name: etcd
    image: 'bitnami/etcd:latest'
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd:2379
    ports:
      - 2379:2379
      - 2380:2380
    networks:
      - app-tier
    restart: always

  etcdkeeper:
    container_name: "etcdkeeper"
    image: "jim3ma/etcdkeeper3"
    environment:
      HOST: etcdkeeper
    networks:
      - app-tier
    ports:
    - 8080:8080
    depends_on:
    - etcd
    restart: always
